language: node_js
node_js:
  - 10
install:
- npm install
- npm run build
before_deploy:
- sudo apt-get -qq update
- sudo apt-get install -y zip
- mv dist/static/android-chrome-192x192.png dist/android-chrome-192x192.png
- mv dist/static/browserconfig.xml dist/browserconfig.xml
- mv dist/static/favicon-32x32.png dist/favicon-32x32.png
- mv dist/static/mstile-150x150.png dist/mstile-150x150.png
- mv dist/static/android-chrome-512x512.png dist/android-chrome-512x512.png
- mv dist/static/favicon.ico dist/favicon.ico
- mv dist/static/safari-pinned-tab.svg dist/safari-pinned-tab.svg
- mv dist/static/apple-touch-icon.png dist/apple-touch-icon.png
- mv dist/static/favicon-16x16.png dist/favicon-16x16.png
- mv dist/static/site.webmanifest dist/site.webmanifest
- git config --local user.name "Bartosz Wiśniewski"
- git config --local user.email "kontakt@pr0gramista.pl"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- cd dist
- zip -r build.zip .
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Kg5KyT2IxA0M+ez1e05U5ujhIVNWMfS++bMNAQwU9DjIaEuAmKzCuA6TnA4nt9TGnUjwRlbEnA3y7LOEP7dbckuFRHF/89VhoATurfFuId7vv6FtBN/rpNnj3E7QkVTWSTiWylWiEJ7lDop4XnW7TTwitMVCRCYRYO5uTYYTFODUd3i2L6JuEhJdiJWJKRIY1cbD5ikw8liDUuDbnSyGhVDDX051sr0/dKfV6UepHr5cCIs6AwvLKSjPa8WOgLewixAJCYcL2+w7gqXPlhjwRefwsSV4XlOuSWTxFUXl79jHumPMq6p6SbgV0B+3eXihN9pOPzQj/iQI+qI6T+0flmdaiaDYx9xE/vKDzHBfVQNdeGlat333lvXQSUVV5nJuZrLh4Y/DBG0twp5mmBaMjwaT6w+N34RabkzrlkomOuVNB+ss1vn2Jr0WxbLjp00Rob4RqeLFkvQVoUT0FEIMSoYOiE32vYSDol/adT+Uw/fW5DZZYqV9GtPDWGYze7aCddmda8x78r8TKyOuMjpvXYPxupbfnBzJUS0DpToiiddVJsOl1Jr/P2CJkCxB2pOg4+UV4l+Azt133M/Z2tPajb5si2ZHZ5H9uDkbw+RipFY+qBN2r5vWR8srQa2vba4ZL9ax4uJGt5SU9W9A2AciwmG06OGJIuEZLQIJEmIK2j8=
  file: build.zip
  on:
    repo: pr0gramista/meme-reader
    tags: true
